language: node_js

node_js:
- 10.8

cache:
  directories:
  - ~/.npm
  - ~/.cache

before_install:
- export TZ=Europe/Amsterdam

before_script:
- cp src/environments/apisettings-test.ts src/environments/apisettings.ts
